Sample/CmsSampleSite/Features/Blocks/RichText/RichTextViewComponent.cs
namespace CmsSampleSite.Features.Blocks.RichText;

using EPiServer.Web.Mvc;

using Microsoft.AspNetCore.Mvc;

public class RichTextBlockViewComponent : BlockComponent<RichTextBlock>
{
    protected override IViewComponentResult InvokeComponent(RichTextBlock currentContent)
    {
        return View(currentContent);
    }
}

Sample/CmsSampleSite/Features/Common/Media/ImageContentViewComponent.cs
namespace CmsSampleSite.Features.Common.Media;

using EPiServer.Web.Mvc;

using Microsoft.AspNetCore.Mvc;

public class ImageContentViewComponent : PartialContentComponent<ImageContent>
{
    protected override IViewComponentResult InvokeComponent(ImageContent currentContent)
    {
        return View(currentContent);
    }
}

Sample/CmsSampleSite/Features/MetaData/MetaDataViewComponent.cs
namespace CmsSampleSite.Features.MetaData;

using CmsSampleSite.Features.Pages;
using CmsSampleSite.Features.Settings;

using EPiServer.Web.Routing;

using Microsoft.AspNetCore.Mvc;

public class MetaDataViewComponent : ViewComponent
{
    private readonly ISiteSettings _siteSettings;
    private readonly UrlResolver _urlResolver;

    public MetaDataViewComponent(ISiteSettings siteSettings, UrlResolver urlResolver)
    {
        _siteSettings = siteSettings;
        _urlResolver = urlResolver;
    }

    public IViewComponentResult Invoke(ISitePageData sitePage)
    {
        var model = new MetaDataViewModel
        {
            Title = $"{_siteSettings?.SiteName} | {sitePage.MetaTitle}",
            Description = sitePage.MetaText,
            Image = _urlResolver.GetUrl(sitePage.MetaImage)
        };

        return View(model);
    }
}

Sample/CmsSampleSite/Features/MetaData/SocialMetaDataViewComponent.cs
namespace CmsSampleSite.Features.MetaData;

using CmsSampleSite.Features.Pages;
using CmsSampleSite.Features.Settings;

using EPiServer.DataAbstraction;

using Microsoft.AspNetCore.Mvc;

public class SocialMetaDataViewComponent : ViewComponent
{
    private readonly ISiteSettings _siteSettings;
    private readonly IContentTypeRepository _contentTypeRepository;

    public SocialMetaDataViewComponent(ISiteSettings siteSettings, IContentTypeRepository contentTypeRepository)
    {
        _siteSettings = siteSettings;
        _contentTypeRepository = contentTypeRepository;
    }

    public IViewComponentResult Invoke(ISitePageData sitePage)
    {
        var contentType = _contentTypeRepository.Load(sitePage.ContentTypeID);

        var model = new SocialMetaDataViewModel
        {
            Title = $"{_siteSettings?.SiteName} | {sitePage.MetaTitle}",
            Description = sitePage.MetaText,
            ImageReference = sitePage.MetaImage ?? sitePage.TeaserImage,
            PageReference = sitePage.ContentLink,
            SiteName = _siteSettings?.SiteName,
            TypeName = contentType?.DisplayName
        };

        return View(model);
    }
}

Sample/CmsSampleSite/Views/ComplexPage/Index.cshtml
@model CmsSampleSite.Features.Pages.Complex.ComplexPageViewModel

<div>
    @Html.PropertyFor(x => x.CurrentPage.HeroImage)
    <h1>@Html.PropertyFor(x => x.CurrentPage.Heading)</h1>

    @if (string.IsNullOrWhiteSpace(Model.TextOne))
    {
        <p>If you add a querystring for parameterOne here, then something else will happen.</p>
    }
    else
    {
        <p>It looks like you entered a value of <em>@Model.TextOne</em> to the querystring for parameterOne.</p>
    }
    @if (string.IsNullOrWhiteSpace(Model.TextTwo))
    {
        <p>If you add a querystring for parameterTwo here, then something else will happen.</p>
    }
    else
    {
        <p>It looks like you entered a value of <em>@Model.TextTwo</em> to the querystring for parameterTwo.</p>
    }

    <div>
        @Html.PropertyFor(x => x.CurrentPage.MainContentArea)
    </div>
</div>

Sample/CmsSampleSite/Views/HomePage/Index.cshtml
@model CmsSampleSite.Features.Pages.Home.HomePageViewModel

<div>
    @Html.PropertyFor(x => x.CurrentPage.HeroImage)
    <h1>@Html.PropertyFor(x => x.CurrentPage.Heading)</h1>
    <div>
        @Html.PropertyFor(x => x.CurrentPage.MainContentArea)
    </div>
</div>

Sample/CmsSampleSite/Views/Shared/Components/ImageContent/Default.cshtml
@model CmsSampleSite.Features.Common.Media.ImageContent

<img src="@Url.ContentUrl(Model.ContentLink)" title="@Model.Title" alt="@Model.AltText"/>

Sample/CmsSampleSite/Views/Shared/Components/MetaData/Default.cshtml
@model CmsSampleSite.Features.MetaData.MetaDataViewModel

<title>@Model.Title</title>
<meta name="description" content="@Model.Description" />

Sample/CmsSampleSite/Views/Shared/Components/RichTextBlock/Default.cshtml
@model CmsSampleSite.Features.Blocks.RichText.RichTextBlock

<div>
    @Html.PropertyFor(x => x.Content)
</div>

Sample/CmsSampleSite/Views/Shared/Components/SocialMetaData/Default.cshtml
@model CmsSampleSite.Features.MetaData.SocialMetaDataViewModel

<!-- twitter meta tags -->
@if (!ContentReference.IsNullOrEmpty(Model.ImageReference))
{
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="@Url.ContentUrl(Model.ImageReference)" />
    <meta name="twitter:image:alt" content="@Model.ImageAltText" />
}
else
{
    <meta name="twitter:card" content="summary">
}
@if (!string.IsNullOrWhiteSpace(Model.Creator))
{
    <meta name="twitter:creator" content="@Model.Creator" />
}
<meta name="twitter:title" content="@Model.Title" />
<meta name="twitter:site" content="@Model.SiteName" />
<meta name="twitter:description" content="@Model.Description" />

<!-- open graph meta tags -->
<meta property="og:site_name" content="@Model.SiteName" />
<meta property="og:url" content="@Url.ContentUrl(Model.PageReference)" />
<meta property="og:title" content="@Model.Title" />
<meta property="og:description" content="@Model.Description" />
<meta property="og:type" content="@Model.TypeName" />
@if (!ContentReference.IsNullOrEmpty(Model.ImageReference))
{
    <meta property="og:image" content="@Url.ContentUrl(Model.ImageReference)" />
}

Sample/CmsSampleSite/Views/Shared/_Layout.cshtml
@using CmsSampleSite.Features.Pages
@model ISitePageViewModel<ISitePageData>

<!DOCTYPE html>
<html lang="en">
<head>
    <vc:meta-data site-page="@Model.CurrentPage"></vc:meta-data>
    <vc:social-meta-data site-page="@Model.CurrentPage"></vc:social-meta-data>

    @await Html.RenderEPiServerQuickNavigatorAsync()
</head>
<body>
    @RenderBody()

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Sample/CmsSampleSite/Views/SimplePage/Index.cshtml
@model CmsSampleSite.Features.Pages.Simple.SimplePageViewModel

<div>
    @Html.PropertyFor(x => x.CurrentPage.HeroImage)
    <h1>@Html.PropertyFor(x => x.CurrentPage.Heading)</h1>
    <div>
        @Html.PropertyFor(x => x.CurrentPage.MainContentArea)
    </div>
</div>